"""fix m2m asksak

Revision ID: 6165ef39c772
Revises: 7dcc0cd214a5
Create Date: 2025-02-10 18:17:18.064569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6165ef39c772'
down_revision: Union[str, None] = '7dcc0cd214a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
