"""Fix bag uniq url

Revision ID: 8acbb4fd62f7
Revises: e7e394db5643
Create Date: 2025-01-19 15:11:08.528496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8acbb4fd62f7'
down_revision: Union[str, None] = 'e7e394db5643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_url_key', 'document', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('document_url_key', 'document', ['url'])
    # ### end Alembic commands ###
