"""mess del

Revision ID: 8c88ee00728b
Revises: f9efb043ed93
Create Date: 2025-02-10 13:56:49.563395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c88ee00728b'
down_revision: Union[str, None] = 'f9efb043ed93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
