"""create order m2m relation with item

Revision ID: 99d7591ca35b
Revises: bd196bfc18d3
Create Date: 2025-02-10 17:55:11.542817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d7591ca35b'
down_revision: Union[str, None] = 'bd196bfc18d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_item_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('order_item_id_fkey', 'order', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###
