"""req cond

Revision ID: a45c8467321c
Revises: 07044a48e284
Create Date: 2025-02-10 15:20:54.642008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45c8467321c'
down_revision: Union[str, None] = '07044a48e284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'condition')
    op.add_column('request', sa.Column('condition', sa.String(), server_default='На рассмотрении', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'condition')
    op.add_column('message', sa.Column('condition', sa.VARCHAR(), server_default=sa.text("'На рассмотрении'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
