"""relation mess-item

Revision ID: da4ddb139da3
Revises: f41a13cd7d65
Create Date: 2025-02-09 23:35:09.926441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4ddb139da3'
down_revision: Union[str, None] = 'f41a13cd7d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_tg_id_key', 'user', ['tg_id'])
    op.drop_column('user', 'role')
    op.drop_column('user', 'email')
    op.drop_column('user', 'password')
    op.drop_column('user', 'username')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'item_id')
    op.create_table('document',
    sa.Column('term', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tg_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registrated_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='document_pkey')
    )
    # ### end Alembic commands ###
