"""mess condition

Revision ID: f9efb043ed93
Revises: da4ddb139da3
Create Date: 2025-02-09 23:40:05.171979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9efb043ed93'
down_revision: Union[str, None] = 'da4ddb139da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('condition', sa.String(), server_default='На рассмотрении', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'condition')
    # ### end Alembic commands ###
