"""Fix bag with uniq

Revision ID: fe8d07d32528
Revises: 8acbb4fd62f7
Create Date: 2025-01-26 14:12:09.075225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8d07d32528'
down_revision: Union[str, None] = '8acbb4fd62f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_name_key', 'document', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('document_name_key', 'document', ['name'])
    # ### end Alembic commands ###
